---
centos_dependencies:
  - python-psycopg2
  - python-setuptools
  - libselinux-python
  - setools-libs
  - yum-utils
  - sudo
  - acl
  - python-pip
  - supervisor
  - "@Development Tools"
  - openssl-devel
  - wget
  - zlib-devel
  - tcl
  - libpqxx-devel.x86_64
