---
# Tasks for configuring PostgreSQL server.

- name: init postgresql
  command: | 
    su postgres -c "/usr/pgsql-10/bin/initdb --pgdata=/var/lib/pgsql/10/data"
  args:
    creates: "{{ pg_conf_dir }}/PG_VERSION"
  become: yes

- name: Make sure PostgreSQL is started
  service:
    name: 'postgresql-10'
    state: started
  register: postgresql_start

- name: Wait for PostgreSQL to start if it wasnt
  wait_for:
    host: localhost
    port: 5432
  when: postgresql_start is changed
