---

- name: Check for old Postgres data
  stat:
    path: "{{ existing_pg_dir }}/PG_VERSION"
  register: old_pg_version_file
  become: yes
  
- name: Install postgres
  yum:
    name: "{{ item }}"
    enablerepo: "pgdg10"
    disable_gpg_check: '{{ not gpgcheck | bool }}'
    state: present
  become: yes
  with_items: "{{ postgresql_packages }}"
