- hosts: "{{ instance_names|default('all') }}"
  become: yes
  gather_facts: yes
  roles:
    - role: repos_el
    - role: dependencies
    - role: postgres
      tags: postgresql_database
      postgres_allowed_ipv4: "0.0.0.0/0"
      postgres_allowed_ipv6: "::/0"
      postgres_username: conduit
      postgres_password: password
      postgres_database: conduit
      max_postgres_connections: 1024
      postgres_shared_memory_size: "{{ (ansible_memtotal_mb*0.1)|int }}"
      postgres_work_mem: "{{ (ansible_memtotal_mb*0.01)|int }}"
      postgres_maintenance_work_mem: "{{ (ansible_memtotal_mb*0.04)|int }}"

  tasks:
    - name: Install system packages
      yum:
        name:
          - python-pip
          - supervisor
          - "@Development Tools"
          - openssl-devel
          - wget
          - zlib-devel
          - tcl
          - libpqxx-devel.x86_64
    # - name: Install Sqlite3 # not needed once postgres is hooked up
    #   shell: "{{ item }}"
    #   with_items:
    #     - wget https://www.sqlite.org/src/tarball/sqlite.tar.gz
    #     - tar xzf sqlite.tar.gz
    #     - cd sqlite && ./configure --prefix=/usr --disable-static CFLAGS="-g"
    #     - cd sqlite && make
    #     - cd sqlite && make install
    - name: Install Python3
      shell: "{{ item }}"
      with_items:
        - wget https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tar.xz
        - tar -xJf Python-3.6.4.tar.xz
        - cd Python-3.6.4 && ./configure --enable-optimizations
        - cd Python-3.6.4 && make altinstall
