- hosts: "{{ instance_names|default('all') }}"
  become: yes
  gather_facts: yes
  tasks:
    - name: Install system packages
      yum:
        name:
          - python-pip
          - supervisor
          - "@Development Tools"
          - openssl-devel
          - wget
          - zlib-devel
          - tcl
          - postgresql
          - libpqxx-devel.x86_64
    # - name: Install Sqlite3 # not needed once postgres is hooked up
    #   shell: "{{ item }}"
    #   with_items:
    #     - wget https://www.sqlite.org/src/tarball/sqlite.tar.gz
    #     - tar xzf sqlite.tar.gz
    #     - cd sqlite && ./configure --prefix=/usr --disable-static CFLAGS="-g"
    #     - cd sqlite && make
    #     - cd sqlite && make install
    - name: Install Python3
      shell: "{{ item }}"
      with_items:
        - wget https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tar.xz
        - tar -xJf Python-3.6.4.tar.xz
        - cd Python-3.6.4 && ./configure --enable-optimizations
        - cd Python-3.6.4 && make altinstall
