---
- name: Prepare Installation Repos
  hosts: "{{ instance_names|default('all') }}"
  become: yes
  gather_facts: yes
  roles:
    - repos_el

- name: Install System Dependencies
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - role: dependencies
      gpgcheck: yes

- name: Set up Database
  hosts: "{{ instance_names|default('all') }}"
  become: yes
  gather_facts: yes
  roles:
    - role: postgres
      tags: postgresql_database
      gpgcheck: yes
      postgres_allowed_ipv4: "0.0.0.0/0"
      postgres_allowed_ipv6: "::/0"
      postgres_username: conduit
      postgres_password: password
      postgres_database: conduit
      max_postgres_connections: 1024
      postgres_shared_memory_size: "{{ (ansible_memtotal_mb*0.1)|int }}"
      postgres_work_mem: "{{ (ansible_memtotal_mb*0.01)|int }}"
      postgres_maintenance_work_mem: "{{ (ansible_memtotal_mb*0.04)|int }}"

- name: Deploy Application
  hosts: "{{ instance_names|default('all') }}"
  become: yes
  gather_facts: yes
  roles:
    - role: app
      app_repo: https://github.com/ansible/django-realworld-example-app
      app_repo_dir: /django-realworld-example-app
      app_name: conduit
      app_wsgi: conduit.wsgi:application
      app_settings_module: conduit.settings_devel
      app_virtualenv_dir: /venv/conduit
      app_virtualenv_python: /usr/local/bin/python3.6
      app_requirements_file: requirements.txt
      app_media_dir: /venv/conduit/media/
      app_static_dir: /venv/conduit/static/
      app_user: conduit
      app_group: conduit
      app_db_name: conduit
      app_db_user: conduit
      app_db_password: password
      app_db_host: '127.0.0.1'
      app_db_port: '5432'
      app_secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

- name: Set up Nginx 
  hosts: "{{ instance_names|default('all') }}"
  become: yes
  gather_facts: yes
  roles:
    - role: nginx
      nginx_app_name: conduit
      nginx_ssl_dest_dir: /etc/ssl
      nginx_static_dir: /venv/conduit/static/
      nginx_media_dir: /venv/conduit/media/
      nginx_virtualenv_dir: /venv/conduit
      nginx_access_log_file: /venv/conduit/logs/nginx_access.log
      nginx_error_log_file:  /venv/conduit/logs/nginx_error.log
