- name: Create GCE Host
  hosts: localhost
  tasks:
    - name: Create GCE Instance(s)
      local_action:
        module: gce
        instance_names: '{{ instance_names }}'
        machine_type: '{{ machine_type }}'
        image: '{{ image }}'
        zone: '{{ zone }}'
        tags: '{{ instance_tags }}'
        disks: '{{ disks | default(omit) }}'
        disk_size: '{{ disk_size | default(omit) }}'
      register: gce_instances
    - name: Wait for SSH
      local_action:
        module: wait_for
        host: '{{ item.public_ip }}'
        port: 22
        delay: 10
        timeout: 60
        state: started
      with_items: '{{ gce_instances.instance_data }}'
    - name: Add hosts group temporary inventory group
      add_host:
        name: '{{ item.public_ip }}'
        groups: dynamic_hosts
      with_items: '{{ gce_instances.instance_data }}'

- name: Set up Access
  hosts: dynamic_hosts
  become: true
  roles:
    - role: access
      replace_sudoers: no
